import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import SectionContainer from "@/components/layouts/SectionContainer";
import MainNavbar from "@/components/layouts/Navbar";
import { ThemeProvider } from "next-themes";
import "./prosemirror.css";
import Footer from "@/components/layouts/Footer";
import { Suspense } from "react";
const roboto = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  isAdmin,
}: Readonly<{
  children: React.ReactNode;
  isAdmin: boolean;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
        <Suspense fallback={<p>..Loading</p>}>
          <ThemeProvider attribute="class">
            <main className="bg-body min-h-screen pb-4 scroll-smooth text-text z-50">
              <SectionContainer>
                <MainNavbar />
                {children}
                <Footer />
              </SectionContainer>
            </main>
          </ThemeProvider>
        </Suspense>
      </body>
    </html>
  );
}
