import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import SectionContainer from "@/components/layouts/SectionContainer";
import MainNavbar from "@/components/layouts/Navbar";
import { ThemeProvider } from "next-themes";
import "./prosemirror.css";
const roboto = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
        <ThemeProvider attribute="class">
          <main className="bg-body min-h-screen pb-4 scroll-smooth text-text z-50">
            <SectionContainer>
              <MainNavbar />
              {children}
            </SectionContainer>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
