import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import SectionContainer from "@/components/layouts/SectionContainer";
import MainNavbar from "@/components/layouts/Navbar";
import { ThemeProvider } from "next-themes";
const roboto = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider attribute="class">
        <body className={roboto.className}>
          <main className="bg-body min-h-screen scroll-smooth text-text">
            <SectionContainer>
              <MainNavbar />
              {children}
            </SectionContainer>
          </main>
        </body>
      </ThemeProvider>
    </html>
  );
}
